spring:
  application:
    name: inventory
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory
    username: ${DB_USER}
    password: ${DB_PASS}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    home: localhost

server:
  port: 8085
