spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create

  cloud:
    function:
      definition: initializeProduct;orderCreated;paymentFailed;paymentSuccess
    stream:
      bindings:
        initializeProduct-in-0:
          destination: product-created
          content-type: application/json
          group: inventory-service-group
        orderCreated-in-0:
          destination: order-created
          content-type: application/json
          group: inventory-service-group
        paymentFailed-in-0:
          destination: payment-failed
          content-type: application/json
          group: inventory-service-group
        paymentSuccess-in-0:
          destination: payment-success
          group: inventory-service-group
          content-type: application/json
        inventoryFailed-out-0:
          destination: inventory-failed
          content-type: application/json
        inventoryReserved-out-0:
          destination: inventory-reserved
          content-type: application/json
        inventoryReverted-out-0:
          destination: inventory-reverted
          content-type: application/json

      kafka:
        binder:
          brokers: localhost:9092


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost

server:
  port: 8085
